post_build:
  commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:latest
    - echo Writing Dockerrun.aws.json file...
    - |
      cat > Dockerrun.aws.json <<EOF
      {
        "AWSEBDockerrunVersion": 1,
        "Image": {
          "Name": "$REPOSITORY_URI:$IMAGE_TAG",
          "Update": "true"
        },
        "Ports": [
          {
            "ContainerPort": "3000"
          }
        ]
      }
      EOF

